Update Build_imm_HLK-7628N.yml

diff --git a/.github/workflows/Build_imm_HLK-7628N.yml b/.github/workflows/Build_imm_HLK-7628N.yml
--- a/.github/workflows/Build_imm_HLK-7628N.yml
+++ b/.github/workflows/Build_imm_HLK-7628N.yml
@@ -207,21 +207,26 @@ jobs:
         echo "status=success" >> $GITHUB_OUTPUT
         
     - name: Generate file list
+      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
       run: |
         find ${{ env.FIRMWARE }} -type f > file_list.txt
+        test -s file_list.txt || { echo "::error::No firmware files found"; exit 1; }
+
 
     - name: Upload firmware to release
+      if: env.UPLOAD_RELEASE == 'true' && steps.organize.outputs.status == 'success'
       uses: ncipollo/release-action@main
       env:
-      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
-      tag: ${{ steps.tag.outputs.release_tag }}
-      bodyFile: release.txt
-      artifacts: file_list.txt
-      artifactErrorsFailBuild: false
-      allowUpdates: true
-      draft: false
-      prerelease: false
+        tag: ${{ steps.tag.outputs.release_tag }}
+        bodyFile: release.txt
+        artifacts: file_list.txt
+        artifactErrorsFailBuild: false
+        allowUpdates: true
+        draft: false
+        prerelease: false
+
 
     - name: Delete old workflow runs via GitHub API
       if: always()
